builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    # GOARM to build for when GOARCH is arm.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Default is only 6.
    goarm:
      - '6'
      - '7'

archives:
  - format: binary