#+TITLE: Jsonnet Language Server

*Warning: This project is in active development and is likely very buggy.*

A *[[https://langserver.org][Language Server Protocol (LSP)]]* server for [[https://jsonnet.org][Jsonnet]].

** Features
  - Jump to definition :: For local variables, import and importstr files, and index targets.
  - Workspace symbols :: Return a hierarchy of document symbols representing /most/ nodes of the Jsonnet AST.
  - Diagnostics :: Static errors and warnings of runtime errors.
  - Formatting :: Format document according to default options.

  Refer to [[file:example.jsonnet][example.jsonnet]] for a documented walkthrough.

** Installation
   To install the LSP server with Go into "${GOPATH}"/bin:
   #+NAME: Installation with Go
   #+BEGIN_SRC shell
   go get -u github.com/jdbaldry/jsonnet-language-server
   #+END_SRC

   To download the latest release binary from GitHub:
   #+NAME: Download from GitHub
   #+BEGIN_SRC shell
   curl -Lo jsonnet-language-server https://github.com/jdbaldry/jsonnet-language-server/releases/latest/download/jsonnet-language-server
   #+END_SRC

   #+RESULTS: Download from GitHub

** Editor integration
   For Emacs, refer to [[file:editor/jsonnet-language-server.el][editor/jsonnet-language-server.el]] for an example of enabling the LSP server with lsp-mode.
